### ISSUE TITLE
Ultrastream incompatable

### ISSUE THREAD

**Issue by tommytoy** [Seko34/Kodi-Development#3]
I have been using Ultrastream for a while and loved it, now since an update it is now incompatable with Jarvis 16.1?????

I noticed you made an update for krypton, but you removed Jarvis???

Please put back Jarvis, Krypton is full of bug and many users dont want to use it yet

**Comment by Seko34** [comment]
No, Jarvis is not removed and should continue to work. But the python version of Jarvis is now deprecated, so you will have some http error with it.

I'll look what 's the problem with Jarvis soon.

**Comment by Seko34** [comment]
I confirm the addon still work on Jarvis.

But Jarvis uses Python 2.6 which supports up to TLS 1.0 only. And directory source which uses 'https' (so TLS version upper to 1.0) connection won't work.

You should change the main source in the settings.

Is it ok?

**Comment by tommytoy** [comment]
Thank you for you respond, but wen you say change the main source in the settings are you talking about the Ultrastrream settings?  The main streaming source is now DPSTREAM, so i should change for another one.

Or you talking about changing in the main Jarvis settings???

**Comment by Seko34** [comment]
I talk about UltraStream settings. You should choose an other source as "DPStream" (this source needs a https connection). Change for "MegaStream" or "Sokrostream" as source in UltraStream settings.

If you need help about UltraStream settings, you could read [the Wiki](https://github.com/Seko34/Kodi-Development/wiki) (in French)  : 
https://github.com/Seko34/Kodi-Development/wiki

**Comment by tommytoy** [comment]
Still not working...here is a screen shot



[cid:ii_03ccff2246774bf2]
Le 5 mars 2017, à 10:30, Seko34 <notifications@github.com<mailto:notifications@github.com>> a écrit:

I talk about UltraStream settings. You should choose an other source as "DPStream" (this source needs a https connection). Change for "MegaStream" or "Sokrostream" as source in UltraStream settings.

If you need help about UltraStream settings, you could read the Wiki<https://github.com/Seko34/Kodi-Development/wiki> (in French) :
https://github.com/Seko34/Kodi-Development/wiki

**Comment by Seko34** [comment]
Please post the image via Github. I can't see it.

Which source have you choosen ? And what is your system ?

**Comment by tommytoy** [comment]
Trying to put the image lolll

**Comment by tommytoy** [comment]
Trying to put the image lolll
https://www.dropbox.com/s/pvafsz53grmrgt1/20170305_155307.png?dl=0

**Comment by tommytoy** [comment]
What is strange is that ultrasyream always did work since you last update.....all my other addons still work

**Comment by Seko34** [comment]
It's seems that the core module has a problem. 
Try to uninstall ultrastream, then reinstall it.

**Comment by Seko34** [comment]
Is the problem solved by uninstall then reinstall the addon ?

**Comment by tommytoy** [comment]
I had some sort of conflict in the build i was using....changing the build fixed the problem.....but couldnt figure out the source of the conflict

**Comment by Seko34** [comment]
Ok, thanks.  I close this issue
